### ISSUE TITLE
Gift Giver Membership Level being set to expire in 3 days.

### ISSUE THREAD

**Issue by darrennye** [strangerstudios/pmpro-gift-levels#8] opened 2018-12-09 23:07 UTC
Hello,

We are trying to use your add-on on taylorstrecker.com. This is an online radio show, and listeners pay $6.95 per month to listen.

We are using current version of PMP and pmpro-customizations and your add-in.

When the site launched, it had one public membership level-id = 1. Incidentally level-id 2 was deleted.

We installed your add-on and added the custom code to pmpro-customizations.php, to allow for a level-id 3 as the gift giver and level-id 4 as the gift recipient.

The add-on works ok if the person buying the gift, is NOT a paying member account. Because the buyer's "Expires" date is not changed.

But most people buying a gift are going to be paying members, who want to give a gift to others to listen.

If the gift buyer is a paying member, and they buy the 6 month gift for someone else, after they do so, their Current Level remains as "Monthly" (isn't that supposed to change to the level 4 of "Buy Gift - 6 months"?) -- and more important their "Expires" date changed from NO to 3 days in the future!!! The Expires field for the gift buyer should NOT be changed!?

Note that the gift recipient account IS correctly set with an expiration date of the 6 months that we set.

Can we please get your help to fix this?

**Comment by greathmaster** [comment] 2018-12-19 03:01
I have re-created this issue on my dev. To reproduce 

*create 3 levels: Monthly, Gift Giver, and Gift Recipient.
*Set gateway to Stripe
*have a member checkout for a recurring subscription to Monthly
*while logged in checkout for the Gift Giver level
*upon confirmation the purchaser will receive a gift code, and their level will not be changed, however they will have an expiration date set a few days from the date of purchase.

**Comment by greathmaster** [comment] 2019-01-09 23:03
This issue was resolved in the v 0.3 update. Also, you will need to upgrade to the latest version of Paid Memberships Pro v 2.0.1, since it contains additional code to support the fix.

**Closed** 2019-01-09 23:03 UTC
